name: Publish website

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  publish_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install documentation dependencies
        run: |
          python3 -m pip install -r requirements/doc_requirements.txt

      - name: Build html website
        run: |
          sphinx-build -b html doc/src build/html

      - name: Deploy website to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true
